name = "MarkableIntegers"
uuid = "0913cafa-90c8-523e-aa68-da9dd2ac225d"
repo = "https://github.com/JeffreySarnoff/MarkableIntegers.jl.git"
author = "Jeffrey Sarnoff"
license = "MIT"
version = "v0.0.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
